import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ParticlesBack from '@/components/particles/ParticlesBack';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Portafolio - Humberto Bracho',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='es' className='!scroll-smooth'>
			<body className={inter.className}>
				{children}

				<ParticlesBack />
			</body>
		</html>
	);
}
